apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./sync.yaml
  - ../../../../../base/apps/podinfo/
patches:
  - path: release-values.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: preconfigs--podinfo
    files:
      - ../../preconfigs/podinfo.yaml
