apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      version: ${PODINFO}
  dependsOn:
    - name: preconfigs--podinfo
  install:
    createNamespace: true
  storageNamespace: ${cluster_name}--podinfo
  targetNamespace: ${cluster_name}--podinfo
  kubeConfig:
    secretRef:
      name: ${target_cluster_kubeconfig_secret}
      key: ${target_cluster_kubeconfig_secret_key}
  values:
    replicaCount: 5
    redis:
      enabled: false
