apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: 6.3.6
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: podinfo
  storageNamespace: podinfo
  targetNamespace: podinfo
