apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deploy-cluster--jt01
resources:
  - ../../namespace-placeholder/
  - sync.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: chart-versions
    envs:
      - ./chart-versions.env
